version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - ">= 13.a, < 14"
  - dependency-name: "@types/node"
    versions:
    - ">= 14.a, < 15"
  - dependency-name: ioredis
    versions:
    - 4.23.0
    - 4.24.2
    - 4.24.3
    - 4.24.4
    - 4.24.5
    - 4.24.6
    - 4.25.0
    - 4.26.0
  - dependency-name: ts-json-schema-generator
    versions:
    - 0.83.2
    - 0.84.0
    - 0.86.1
    - 0.88.0
    - 0.89.0
    - 0.89.1
    - 0.89.2
    - 0.89.3
    - 0.90.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: nodemailer
    versions:
    - 6.5.0
  - dependency-name: config
    versions:
    - 3.3.4
  - dependency-name: "@types/js-yaml"
    versions:
    - 4.0.0
  - dependency-name: js-yaml
    versions:
    - 4.0.0
  - dependency-name: "@types/ioredis"
    versions:
    - 4.19.3
    - 4.19.4
  - dependency-name: "@types/mailparser"
    versions:
    - 3.0.1
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
