kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-mail:policies
rules:
- apiGroups: ["kube-mail.helmich.me"]
  resources: ["emailpolicies", "smtpservers"]
  verbs:
  - get
  - list
  - watch
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["smtp-credentials"]
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-mail:podwatcher
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs:
  - get
  - list
  - watch


---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ template "chart.fullname" . }}


---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-mail:{{ template "chart.fullname" . }}:podwatcher
subjects:
- kind: ServiceAccount
  name: {{ template "chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: kube-mail:podwatcher
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-mail:{{ template "chart.fullname" . }}:policies
subjects:
- kind: ServiceAccount
  name: {{ template "chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: kube-mail:policies
  apiGroup: rbac.authorization.k8s.io